spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
    url: "jdbc:h2:mem:3"
    username: sa
    password:
  data: data.sql


