export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const GET_CUSTOMER_ACCOUNTS = 'GET_CUSTOMER_ACCOUNTS';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const ADD_NEW_CUSTOMER = 'ADD_NEW_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const CHANGE_CUSTOMER_DATA = 'CHANGE_CUSTOMER_DATA';
export const OPEN_ACCOUNT = 'OPEN_ACCOUNT';

