export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const GET_CUSTOMER_ACCOUNTS = 'GET_CUSTOMER_ACCOUNTS';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const ADD_NEW_CUSTOMER = 'ADD_NEW_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const CHANGE_CUSTOMER_DATA = 'CHANGE_CUSTOMER_DATA';
export const OPEN_ACCOUNT = 'OPEN_ACCOUNT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const DELETE_CUSTOMER_ACCOUNT = 'DELETE_CUSTOMER_ACCOUNT';
export const GET_ACCOUNTS = 'GET_ACCOUNTS';
export const TOP_UP_ACCOUNT = 'TOP_UP_ACCOUNT';
export const WITHDRAW_ACCOUNT = 'WITHDRAW_ACCOUNT';
export const SEND_MONEY = 'SEND_MONEY';
export const ADD_NEW_EMPLOYER = 'ADD_NEW_EMPLOYER';
export const GET_EMPLOYERS = 'GET_EMPLOYERS';
export const DELETE_EMPLOYER_BY_ID = 'GET_EMPLOYERS';
export const FIND_CUSTOMER_BY_NAME = 'FIND_CUSTOMER_BY_NAME';
export const GET_CUSTOMERS_AMOUNT = 'GET_CUSTOMERS_AMOUNT';
export const GET_CUSTOMERS_PAGINATION = 'GET_CUSTOMERS_PAGINATION'


